// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa6JpwNkmr2vBOTz-ysKw061Vav2WRYII',
    appId: '1:254375422140:web:8537445a0c4b15f95a88b9',
    messagingSenderId: '254375422140',
    projectId: 'hrm-attendance-d0494',
    authDomain: 'hrm-attendance-d0494.firebaseapp.com',
    storageBucket: 'hrm-attendance-d0494.firebasestorage.app',
    measurementId: 'G-ESM46NLQ9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsvjAyPlj9WNjnybVaQ0ZZdkiIKT2Kwug',
    appId: '1:254375422140:android:4e5bc0a4948d09eb5a88b9',
    messagingSenderId: '254375422140',
    projectId: 'hrm-attendance-d0494',
    storageBucket: 'hrm-attendance-d0494.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOiUX-yRTSL3vt14-mVtAMNE9Pj7w5PCE',
    appId: '1:254375422140:ios:68cac080fe3d9bc85a88b9',
    messagingSenderId: '254375422140',
    projectId: 'hrm-attendance-d0494',
    storageBucket: 'hrm-attendance-d0494.firebasestorage.app',
    iosBundleId: 'com.example.hrmAttendanceProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa6JpwNkmr2vBOTz-ysKw061Vav2WRYII',
    appId: '1:254375422140:web:407161764c9c64865a88b9',
    messagingSenderId: '254375422140',
    projectId: 'hrm-attendance-d0494',
    authDomain: 'hrm-attendance-d0494.firebaseapp.com',
    storageBucket: 'hrm-attendance-d0494.firebasestorage.app',
    measurementId: 'G-8QXJZJS3NF',
  );
}
